"""initial schema

Revision ID: 5f6a776329d1
Revises:
Create Date: 2026-07-07 22:37:04.442941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5f6a776329d1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("tmdb_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tmdb_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "episodes",
        sa.Column("tmdb_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("series_tmdb_id", sa.Integer(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["series_tmdb_id"], ["series.tmdb_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tmdb_id"),
        sa.UniqueConstraint("series_tmdb_id", "season_number", "episode_number"),
    )
    op.create_index(
        op.f("ix_episodes_series_tmdb_id"), "episodes", ["series_tmdb_id"], unique=False
    )
    op.create_table(
        "user_series",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("series_tmdb_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["series_tmdb_id"],
            ["series.tmdb_id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "series_tmdb_id"),
    )
    op.create_table(
        "watched_episodes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("episode_tmdb_id", sa.Integer(), nullable=False),
        sa.Column(
            "watched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_tmdb_id"], ["episodes.tmdb_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "episode_tmdb_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watched_episodes")
    op.drop_table("user_series")
    op.drop_index(op.f("ix_episodes_series_tmdb_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_table("users")
    op.drop_table("series")
    # ### end Alembic commands ###
